const types = {
  GET_ALL_CLOTHES: "GET_ALL_CLOTHES",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  GET_PAGE: "GET_PAGE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  UPDATE_FILTERS: "UPDATE_FILTERS",
  CLEAN_PAGE: 'CLEAN_PAGE',
  CLEAN_DETAIL: 'CLEAN_DETAIL',
};

export default types;
